build:
  tests:
    override:
      - pylint-run --rcfile=.pylint.ini
  nodes:
    py35:
      environment:
        python: 3.5.1
    py36:
      environment:
        python: 3.6
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  excluded_paths:
    - "*/tests/*"
