site_name: GDM
site_description: A language-agnostic "dependency manager" using Git.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/gdm
google_analytics: ['UA-6468614-11', 'git-dependency-manager.info']

theme: mkdocs

pages:
- Home: 'index.md'
#- 'Use Cases':
  # - TBD: example.md
  # - TBD: example2.md
- About:
  - License: 'about/license.txt'
  - Contributing: 'about/contributing.md'
  - 'Release Notes': 'about/changes.md'
